apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sanepa-example-deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sanepa
        monitoring: example-deployment
    spec:
      serviceAccountName: sanepa-service-account
      containers:
        - name: sanepa
          image: mitchya1/sanepa:v1-k8s1.15.7-latest
          command: ["/sanepa"]
          args:
            - "-incluster=true"
            - "-ns=test"
            - "-dep=example-deployment"
            - "-cpu=50"
            - "-mem=60"
            - "-min=2"
            - "-max=4"
            - "-cooldown=100"
            - "-scaledownok=5"
          resources:
              limits:
                memory: "50Mi"
                cpu: "50m"
              requests:
                memory: "10Mi"
                cpu: "10m"
          terminationMessagePath: "/tmp/term.log"