apiVersion: v1
kind: ServiceAccount
metadata:
  name: sanepa-service-account
  namespace: default
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: sanepa-cr
rules:
 - apiGroups: ["metrics.k8s.io"]
   resources: ["pods"]
   verbs: ["get", "list"]
 - apiGroups: ["extensions"]
   resources: ["deployments"]
   verbs: ["get", "list", "patch", "update"]
 - apiGroups: ["apps"]
   resources: ["deployments", "deployments/scale"]
   verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sanepa-crb
  namespace: default
subjects:
- kind: ServiceAccount
  name: sanepa-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: sanepa
  apiGroup: rbac.authorization.k8s.io