apiVersion: apps/v1
kind: Deployment
metadata:
  name: sanepa-example-deployment
  namespace: default
spec:
  replicas: 1
  selectors:
    matchLabels:
      app: sanepa
  template:
    metadata:
      labels:
        app: sanepa
        monitoring: example-deployment
    spec:
      serviceAccountName: sanepa-service-account
      containers:
        - name: sanepa
          image: mitchya1/sanepa:v1-k8s1.16.8-latest
          command: ["/sanepa"]
          args:
            - "-incluster=true"
            - "-ns=test"
            - "-dep=example-deployment"
            - "-cpu=50"
            - "-mem=60"
            - "-min=2"
            - "-max=4"
            - "-cooldown=100"
            - "-scaledownok=5"
            - "-scaleupok=2"
            - "-gl-enabled=true"
            - "-gl-server=10.10.5.44:15151"
            - "-breachpercentthreshold=25"
          resources:
              limits:
                memory: "50Mi"
                cpu: "20m"
              requests:
                memory: "10Mi"
                cpu: "10m"
          terminationMessagePath: "/tmp/term.log"