name: 'Build and Push'
on:
  push:
    branches:
      - 1.16.8
jobs:
  build_go:
    name: 'Build Go binary'
    runs-on: ubuntu-18.04
    steps:
    - name: 'Build Go binary'
      run: "echo $PWD"
      #working-directory: 
  build_push_docker:
    name: 'Build and push SanePA Docker container'
    needs: build_go
    runs-on: 'ubuntu-18.04'
    steps:
    - name: 'Build and push SanePA Docker container'
      env:
        DOCKER_USERNAME: mitchya1
        DOCKER_PASSWORD: '${{ secrets.DOCKERHUB_PASSWORD }}'
      run: bash ./helpers/dockerpush.sh
